@startuml
  hide circle
  skinparam classAttributeIconSize 0
  top to bottom direction
  title FinTrack Core Module Overview

  class FinTrack
  class Ui
  class Parser
  class FinanceManager
  interface Storage
  FinTrack ..> FinanceManager : invoke commands
  FinTrack ..> Parser : parse commands
  FinTrack ..> Ui : render messages
  FinTrack ..> Storage : delegate export
  CsvStorage ..|> Storage
  FinTrack ..> CsvStorage : default storage
  Parser ..> Ui : use command prefixes

  @enduml